aliases:
  docker: &docker
    docker:
      - image: heydovetail/node:node-10.3.0-yarn-1.7.0-npm-5.6.0-awscli-1.15.3
        environment:
          SENTRY_DSN: https://326d6efba0f941a1b9848ce52e78d761@sentry.io/1189595

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - node-modules-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: |
        yarn

  cache_node_modules: &cache_node_modules
    save_cache:
      name: Save node modules cache
      key: node-modules-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

  deploy: &deploy
    run:
      name: Deploy
      command: |
        # Upload all non .html files, we don't want to delete items in the
        # bucket as they may still be requested by users who have an old version
        # of the page open and navigate the single-page-app.
        aws s3 sync --exclude "*.html" --acl public-read public/ s3://${S3_BUCKET_NAME}
        # Sync .html files, deleting orphaned files from the bucket to prevent
        # old index pages from preventing users from hitting the 404 page. For
        # example we removed the /product index page, but previously we had left
        # the .html in place which caused people to hit the wrong page when
        # navigating to /product.
        aws s3 sync --exclude "*" --include "*.html" --delete --acl public-read public/ s3://${S3_BUCKET_NAME}
        aws configure set preview.cloudfront true
        aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'

version: 2
jobs:
  build_and_test_and_deploy_stg:
    <<: *docker
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *cache_node_modules
      - run:
          name: Configure build
          command: |
            echo "export SENTRY_RELEASE=$(git log -n 1 --pretty=format:"%H")" >> $BASH_ENV
      - run: yarn build
      - run: yarn test
      - run:
          name: Configure deployment
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            echo 'export CLOUDFRONT_DISTRIBUTION_ID=$STAGING_CLOUDFRONT_DISTRIBUTION_ID' >> $BASH_ENV
            echo 'export S3_BUCKET_NAME=$STAGING_S3_BUCKET_NAME' >> $BASH_ENV
      - <<: *deploy
    environment:
      GATSBY_BASE_URL: https://dovetailappstg.com
      PREVENT_CRAWLING: true
      SENTRY_ENVIRONMENT: staging

  build_and_deploy_prod:
    <<: *docker
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *cache_node_modules
      - run:
          name: Configure build
          command: |
            echo "export SENTRY_RELEASE=$(git log -n 1 --pretty=format:"%H")" >> $BASH_ENV
      - run: yarn build
      - run:
          name: Configure deployment
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            echo 'export CLOUDFRONT_DISTRIBUTION_ID=$PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID' >> $BASH_ENV
            echo 'export S3_BUCKET_NAME=$PRODUCTION_S3_BUCKET_NAME' >> $BASH_ENV
      - <<: *deploy
    environment:
      GATSBY_BASE_URL: https://dovetailapp.com
      PREVENT_CRAWLING: false
      SENTRY_ENVIRONMENT: production

  build_and_test:
    <<: *docker
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *cache_node_modules
      - run: yarn build
      - run: yarn test

workflows:
  version: 2

  master_branch:
    jobs:
      - build_and_test_and_deploy_stg:
          filters:
            branches:
              only:
                - master

  deploy_production_branch:
    jobs:
      - build_and_deploy_prod:
          filters:
            branches:
              only:
                - deploy/production

  other_branches:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - /deploy\/.+/
                - master
